### ISSUE TITLE
Update to Godot 4.0

### ISSUE THREAD

**Issue by kxkw** [YuriSizov/godot-time-tracker#5]
This plugin looks awesome! I really like the simple design and easy to read infographics of your project work time. 

Will it ever be updated to work with Godot 4.0?

**Comment by YuriSizov** [comment]
Hey, sure! I don't have a concrete timeframe for that, but it should be easy to port. PRs are welcome, of course, but I will try to find some time myself as well.

**Comment by YuriSizov** [comment]
Support for 4.0/4.1 has been added in https://github.com/YuriSizov/godot-time-tracker/commit/4bc21a24d76f64295793a4002f8c98964d1aff60. I haven't turned this into a full release yet, as I want to look into some improvements first. But you can already download and use it.
